quotes = {
    "johnny": [
        "Quiet! Listen up.",
        "Strike first, strike hard, no mercy.",
        "You gotta be a badass.",
        "The best defense is more offense.",
        "I don't need a handout, I need a hand.",
        "Kicks get chicks",
        "Makes Me Feel Like A Virgin Just Looking At You.",
        "Quiet!",
        "A Coors Banquet For Me, And A Shirley Temple For The Lady.",
        "Two Cobras In The Jungle - One Kills The Strongest Lion, The Other Kills A Crippled Monkey. Which Cobra Do You Want To Be?",
        "It Doesn't Matter If You're A Loser, Or A Nerd, Or A Freak! All That Matters Is That You Become Badass!",
        "When You Came To Me You Were Softer Than A Baby's Ass",
        "I Don't Want To Screw Things Up With Miguel. Then Again, You're Pretty Hot.",
        "They Strike First, We'll Pre-Strike!",
        "We Need 4,000 Pesos, That's Like A Million Dollars.",
        "Thanks For Being A Dork, Or Geek, Or Whatever You Identify As.",
        "Same reason there aren't women in the army, doesn't make sense.",
        "Pain does not exist in this dojo!",
        "We're all gonna die kid. We're all gonna die.",
    ],
    "daniel": [
        "Wax on, wax off.",
        "It's not about how you hit the mat, it's about how you get up.",
        "Balance is key.",
        "The best defense is to not be there.",
        "You do the right thing cause it's the right thing to do."
    ],
    "miguel": [
        "I don't want to be the last one standing alone.",
        "I'm ready, sensei.",
        "I won't let you down.",
        "Cobra Kai never dies.",
        "There's no honor in being merciless.",
    ],
}